version: '3.2'
services:
  influxsrv:
    image: influxdb:1.3.1-alpine
    ports:
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    environment:
      - PRE_CREATE_DB=cadvisor
  cadvisor:
    image: google/cadvisor:v0.26.1
    deploy:
      mode: global
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    ports:
      - "9090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    links:
      - influxsrv:influxsrv
  grafana:
    image: grafana/grafana:4.4.1
    ports:
      - "3000:3000"
    links:
      - influxsrv:influxsrv
    environment:
      - INFLUXDB_HOST=influxsrv
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
    labels:
      aliyun.routing.port_3000: 'http://grafana'
  config:
    image: registry.aliyuncs.com/acs-sample/grafana-config:0.9
    links:
      - influxsrv:influxsrv
      - grafana:grafana
